remote_theme: just-the-docs/just-the-docs
# theme: jekyll-theme-minimal
title: Bitácora
description: Lugar donde el comportamiento sistemático y lleno de incertidumbre crecen con el tiempo y afectan el espacio que compartimos. 
